// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// analyser
arma::mat analyser(arma::vec x, double threshold, int window);
RcppExport SEXP _fever_analyser(SEXP xSEXP, SEXP thresholdSEXP, SEXP windowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    rcpp_result_gen = Rcpp::wrap(analyser(x, threshold, window));
    return rcpp_result_gen;
END_RCPP
}
// rainfall_events
arma::mat rainfall_events(arma::vec x, double value_threshold, double event_threshold, int n_max_event_time, int n_roll_max_event);
RcppExport SEXP _fever_rainfall_events(SEXP xSEXP, SEXP value_thresholdSEXP, SEXP event_thresholdSEXP, SEXP n_max_event_timeSEXP, SEXP n_roll_max_eventSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type value_threshold(value_thresholdSEXP);
    Rcpp::traits::input_parameter< double >::type event_threshold(event_thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type n_max_event_time(n_max_event_timeSEXP);
    Rcpp::traits::input_parameter< int >::type n_roll_max_event(n_roll_max_eventSEXP);
    rcpp_result_gen = Rcpp::wrap(rainfall_events(x, value_threshold, event_threshold, n_max_event_time, n_roll_max_event));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fever_analyser", (DL_FUNC) &_fever_analyser, 3},
    {"_fever_rainfall_events", (DL_FUNC) &_fever_rainfall_events, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_fever(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
