# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Analyse an xts object
#' @description Get start and end points where a given threshold is
#' satisfied.
#' @param x The xts object to be analyzed.
#' @param threshold The minimum threshold.
#' @param window The search window.
#' @return A 2-column matrix with start and end indices.
#' @export
analyser <- function(x, threshold, window) {
    .Call(`_fever_analyser`, x, threshold, window)
}

#' @title Analyse an xts object
#' @description Get start and end points where a given threshold and event sum 
#' within a given time is satisfied.
#' @param x The xts object to be analyzed.
#' @param value_threshold The minimum threshold for individual timestep.
#' @param event_threshold The threshold for relevant event within sep-time
#' @param n_max_event_time The search window / separation time per event. 
#' @return A 2-column matrix with start and end indices.
#' @export
rainfall_events <- function(x, value_threshold = 0.01, event_threshold = 0.5, n_max_event_time = 48L, n_roll_max_event = 12L) {
    .Call(`_fever_rainfall_events`, x, value_threshold, event_threshold, n_max_event_time, n_roll_max_event)
}

